# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        kaggle: 2
        instance segmentation: 3
        detection: 4
        segmentation: 3
        edge AI: 4

# 通知の閾値
score_threshold: 0
